package com.github.russp.jtorrt.rpc.qbittorrent;

import io.avaje.jsonb.Json;

import java.math.BigDecimal;

@Json
public record TorrentInfo(
		long added_on,
		long amount_left,
		boolean auto_tmm,
		BigDecimal availability,
		String category,
		long completed,
		long completion_on,
		String content_path,
		long dl_limit,
		long dlspeed,
		String download_path,
		long downloaded,
		long downloaded_session,
		long eta,
		boolean f_l_piece_prio,
		boolean force_start,
		String hash,
		long inactive_seeding_time_limit,
		String infohash_v1,
		String infohash_v2,
		long last_activity,
		String magnet_uri,
		long max_inactive_seeding_time,
		double max_ratio,
		long max_seeding_time,
		String name,
		long num_complete,
		long num_incomplete,
		long num_leechs,
		long num_seeds,
		long priority,
		double progress,
		double ratio,
		long ratio_limit,
		String save_path,
		long seeding_time,
		long seeding_time_limit,
		long seen_complete,
		boolean seq_dl,
		long size,
		String state,
		boolean super_seeding,
		String tags,
		long time_active,
		long total_size,
		String tracker,
		int trackers_count,
		int up_limit,
		long uploaded,
		long uploaded_session,
		long upspeed
) {
}
